version: '2'
services:
    licitacao-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/licitacao/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=licitacao
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
